import { FlowConversionPlan, FlowPlanCondition, FlowPlanConfidence, FlowPlanNode, FlowPlanValue, FluentSourceFile } from "./WorkflowConversionModels";

/**
 * Writes a Fluent (now-sdk) skeleton for a {@link FlowConversionPlan}: one `.now.ts` file with
 * the flow (or subflow), its trigger, flow variables and body. Everything the plan could not
 * carry over is a `TODO(convert)` comment at the place it belongs, with the legacy script or
 * settings to work from, and the plan's open decisions head the file.
 *
 * The output targets @servicenow/sdk 4.12+ and builds as is: steps that need design work are
 * comments, and conditions that could not be derived are empty. It is a starting point to
 * review, not a flow to deploy unread.
 */

export interface FluentGeneratorOptions {
    /** Folder inside the now-sdk app for the flow file (default `src/fluent/flows`) */
    directory?: string;
}

const INDENT = '    ';

/** Generate the Fluent source for a conversion plan. */
export function generateFluentFlow(plan: FlowConversionPlan, opts: FluentGeneratorOptions = {}): FluentSourceFile[] {
    const g = new Generator(plan);
    const directory = (opts.directory ?? 'src/fluent/flows').replace(/\/+$/, '');
    return [{ path: `${directory}/${plan.identifier.replace(/_/g, '-')}.now.ts`, content: g.file() }];
}

class Generator {
    private readonly _lines: string[] = [];
    private readonly _imports = { automation: new Set<string>(['wfa']), core: new Set<string>() };

    public constructor(private readonly plan: FlowConversionPlan) {}

    public file(): string {
        const body = this.definition();
        const head: string[] = [];
        head.push(`import { ${[...this._imports.automation].sort().join(', ')} } from '@servicenow/sdk/automation'`);
        if (this._imports.core.size) head.push(`import { ${[...this._imports.core].sort().join(', ')} } from '@servicenow/sdk/core'`);
        head.push('', ...this.header(), '');
        return `${[...head, ...body].join('\n')}\n`;
    }

    // -------------------------------------------------------------- file parts

    private header(): string[] {
        const p = this.plan;
        const lines = [
            `${p.name}: generated by now-sdk-ext from the legacy workflow "${p.source.name}"`,
            `(wf_workflow ${p.source.workflowSysId}, version ${p.source.versionSysId}, table ${p.source.table}).`,
            '',
            'A starting point, not a finished flow: work through every TODO(convert) before deploying.',
            `Coverage: ${p.coverage.direct} steps carried over directly, ${p.coverage.partial} partly, ${p.coverage.manual} to design by hand.`,
        ];
        if (p.trigger.notes.length) lines.push('', 'Trigger:', ...p.trigger.notes.map(n => `  - ${n}`));
        const custom = customFields(p);
        if (custom.length) {
            lines.push('', `Custom fields used as data pills: ${custom.join(', ')}. The build types them from the app's table dependencies: `
                + `list ${p.trigger.table} under dependencies in now.config.json and run \`now-sdk dependencies\`.`);
        }
        if (p.openDecisions.length) lines.push('', 'Open decisions:', ...p.openDecisions.map(d => `  - [${d.topic}] ${d.detail}`));
        return blockComment(lines.flatMap(l => (l ? wrap(l, 110) : [l])), '');
    }

    private definition(): string[] {
        const p = this.plan;
        const out: string[] = [];
        const name = camel(p.identifier);
        const [i2, i3] = [INDENT.repeat(2), INDENT.repeat(3)];
        const config = [
            `${i2}$id: Now.ID[${str(p.identifier)}],`,
            `${i2}name: ${str(p.name)},`,
            `${i2}description: ${str(`Converted from the legacy workflow "${p.source.name}".`)},`,
            `${i2}runAs: 'system',`,
        ];
        if (p.kind === 'subflow') {
            this._imports.automation.add('Subflow');
            config.push(`${i2}inputs: {`);
            if (p.trigger.recordPill) {
                this._imports.core.add('ReferenceColumn');
                config.push(`${i3}record: ReferenceColumn({ label: 'Record', referenceTable: ${str(p.trigger.table)}, mandatory: true }),`);
            }
            for (const input of p.trigger.inputs.filter(i => i.name !== 'record')) {
                config.push(`${i3}${key(input.name)}: ${this.column(columnType(input.type), input.label || input.name, input.mandatory)},`);
            }
            config.push(`${i2}},`, `${i2}outputs: {},`);
        } else {
            this._imports.automation.add('Flow');
            this._imports.automation.add('trigger');
        }
        if (p.flowVariables.length) {
            config.push(`${i2}flowVariables: {`, ...p.flowVariables.map(v => `${i3}${key(v.name)}: ${this.column(v.type, humanize(v.name))},`), `${i2}},`);
        } else config.push(`${i2}flowVariables: {},`);

        out.push(`export const ${name} = ${p.kind === 'subflow' ? 'Subflow' : 'Flow'}(`, `${INDENT}{`, ...config, `${INDENT}},`);
        if (p.kind === 'flow') out.push(`${INDENT}${this.trigger()},`);
        this.emit(p.steps, 2, 0);
        // the build rejects an unused parameter
        const usesParams = this._lines.some(l => /\bparams\./.test(l.replace(/^\s*(\/\/|\*).*$/, '')));
        out.push(`${INDENT}(${usesParams ? 'params' : ''}) => {`);
        out.push(...this._lines);
        out.push(`${INDENT}}`, ')');
        return out;
    }

    private trigger(): string {
        const t = this.plan.trigger;
        const id = `{ $id: Now.ID[${str(`${this.plan.identifier}_trigger`)}] }`;
        if (t.kind === 'serviceCatalog') return `wfa.trigger(trigger.application.serviceCatalog, ${id}, { run_flow_in: 'background' })`;
        const event = t.recordEvent === 'createdOrUpdated' ? 'createdOrUpdated' : 'created';
        return `wfa.trigger(trigger.record.${event}, ${id}, { table: ${str(t.table)}, condition: ${str(t.condition ?? '')}, run_flow_in: 'background' })`;
    }

    private column(type: 'string' | 'boolean' | 'integer', label: string, mandatory = false): string {
        const fn = type === 'boolean' ? 'BooleanColumn' : type === 'integer' ? 'IntegerColumn' : 'StringColumn';
        this._imports.core.add(fn);
        return `${fn}({ label: ${str(label)}${mandatory ? ', mandatory: true' : ''} })`;
    }

    // -------------------------------------------------------------- body

    private emit(nodes: FlowPlanNode[], depth: number, parallelDepth: number): void {
        const pad = INDENT.repeat(depth);
        const push = (...lines: string[]): void => {
            this._lines.push(...lines.map(l => (l ? pad + l : l)));
        };
        const id = (suffix: string): string => `Now.ID[${str(`${this.plan.identifier}_${suffix}`)}]`;
        const step = (n: FlowPlanNode): string => (n.source.number ? `step ${n.source.number}: ${n.source.name}` : n.source.name);

        for (const n of nodes) {
            switch (n.kind) {
                case 'action': {
                    this._imports.automation.add('action');
                    push(...headline(n.confidence), ...notesComment(n.notes, 'note'));
                    if (n.action === 'action.core.askForApproval') {
                        const rules = n.inputs.approval_conditions;
                        if (rules?.kind === 'approvalRules' && !rules.users.length && !rules.groups.length) push('// TODO(convert): no approvers could be carried over; set users or groups.');
                    }
                    const call = `wfa.action(${n.action}, { $id: ${id(n.id)}, annotation: ${str(`Legacy ${step(n)}`)} }, {`;
                    push(n.output ? `const ${n.output} = ${call}` : call);
                    for (const [k, v] of Object.entries(n.inputs)) push(`${INDENT}${key(k)}: ${this.value(v, k, depth + 1)},`);
                    push('})');
                    break;
                }
                case 'waitForADuration':
                    push(...headline(n.confidence), ...notesComment(n.notes, 'note'));
                    push(`wfa.flowLogic.waitForADuration({ $id: ${id(n.id)}, annotation: ${str(`Legacy ${step(n)}`)}, durationType: 'explicit_duration', duration: ${duration(n.seconds)} })`);
                    break;
                case 'setFlowVariables':
                    push(...notesComment(n.notes, 'note'));
                    push(`wfa.flowLogic.setFlowVariables({ $id: ${id(n.id)}, annotation: ${str(`Legacy ${step(n)}`)} }, params.flowVariables, {`);
                    for (const [k, v] of Object.entries(n.values)) push(`${INDENT}${key(k)}: ${this.value(v, k, depth + 1)},`);
                    push('})');
                    break;
                case 'if': {
                    push(...notesComment(n.notes, 'note'));
                    n.branches.forEach((b, i) => {
                        push(...conditionComment(b.condition));
                        push(`wfa.flowLogic.${i ? 'elseIf' : 'if'}({ $id: ${id(i ? `${n.id}_${i}` : n.id)}, condition: ${condition(b.condition)}, annotation: ${str(`${b.label} (legacy ${step(n)})`)} }, () => {`);
                        this.block(b.body, depth + 1, parallelDepth);
                        push('})');
                    });
                    if (n.otherwise) {
                        push(`wfa.flowLogic.else({ $id: ${id(`${n.id}_else`)}, annotation: ${str(`${n.otherwise.label} (legacy ${step(n)})`)} }, () => {`);
                        this.block(n.otherwise.body, depth + 1, parallelDepth);
                        push('})');
                    }
                    break;
                }
                case 'parallel':
                    if (parallelDepth > 0) {
                        push(...notesComment([...n.notes, `These ${n.lanes.length} lines ran in parallel in the workflow (legacy ${step(n)}); they run one after the other here.`], 'TODO(convert)'));
                        n.lanes.forEach((lane, k) => {
                            push(`// line ${k + 1}`);
                            this.emit(lane, depth, parallelDepth);
                        });
                        break;
                    }
                    push(...notesComment(n.notes, 'note'));
                    push(`wfa.flowLogic.doInParallel(`, `${INDENT}{ $id: ${id(n.id)}, annotation: ${str(`Parallel lines after legacy ${step(n)}`)} },`);
                    n.lanes.forEach(lane => {
                        push(`${INDENT}() => {`);
                        this.block(lane, depth + 2, parallelDepth + 1);
                        push(`${INDENT}},`);
                    });
                    push(')');
                    break;
                case 'endFlow':
                    push(`wfa.flowLogic.endFlow({ $id: ${id(n.id)}, annotation: ${str(`Legacy ${step(n)}`)} })`);
                    break;
                case 'todo':
                    push(...notesComment([`${n.reason} (legacy ${step(n)})`], 'TODO(convert)'));
                    if (n.detail) push(...blockComment(n.detail.replace(/\r\n/g, '\n').split('\n'), ''));
                    break;
            }
        }
    }

    /** The body of a branch or a parallel line; an empty one says so. */
    private block(nodes: FlowPlanNode[], depth: number, parallelDepth: number): void {
        if (nodes.length) this.emit(nodes, depth, parallelDepth);
        else this._lines.push(`${INDENT.repeat(depth)}// carries on with the steps after this decision`);
    }

    private value(v: FlowPlanValue, inputName: string, depth: number): string {
        switch (v.kind) {
            case 'literal':
                return typeof v.value === 'string' ? str(v.value) : String(v.value);
            case 'pill':
                return `wfa.dataPill(${v.expr}, ${str(v.type)})`;
            case 'text':
                return `\`${v.parts.map(p => (typeof p === 'string' ? escapeTemplate(p) : `\${wfa.dataPill(${p.expr}, ${str(p.type)})}`)).join('')}\``;
            case 'template': {
                const fields = Object.entries(v.fields).map(([k, x]) => `${INDENT.repeat(depth + 1)}${key(k)}: ${this.value(x, k, depth + 1)},`);
                return fields.length ? `TemplateValue({\n${fields.join('\n')}\n${INDENT.repeat(depth)}})` : 'TemplateValue({})';
            }
            case 'approvalRules': {
                const list = (items: FlowPlanValue[]): string => `[${items.map(x => this.value(x, inputName, depth)).join(', ')}]`;
                const pad = INDENT.repeat(depth);
                return [
                    'wfa.approvalRules({',
                    `${pad}${INDENT}conditionType: 'OR',`,
                    `${pad}${INDENT}ruleSets: [{`,
                    `${pad}${INDENT}${INDENT}action: ${str(v.action)},`,
                    `${pad}${INDENT}${INDENT}conditionType: 'AND',`,
                    `${pad}${INDENT}${INDENT}rules: [[{ ruleType: ${str(v.ruleType)}, users: ${list(v.users)}, groups: ${list(v.groups)}, manual: false }]],`,
                    `${pad}${INDENT}}],`,
                    `${pad}})`,
                ].join('\n');
            }
            case 'duration':
                return duration(v.seconds);
            case 'list':
                // recipient lists are comma-separated text
                return this.value({ kind: 'text', parts: v.items.flatMap((x, i) => [...(i ? [','] : []), x.kind === 'pill' ? { expr: x.expr, type: x.type } : String(x.kind === 'literal' ? x.value : '')]) }, inputName, depth);
        }
    }
}

// ------------------------------------------------------------------ helpers

/** Custom (u_) fields of the workflow's record referenced through data pills. */
function customFields(plan: FlowConversionPlan): string[] {
    const found = new Set<string>();
    const record = plan.trigger.recordPill;
    const scan = (text: string): void => {
        if (!record) return;
        for (const m of text.matchAll(new RegExp(`${record.replace(/\./g, '\\.')}\\.([\\w.]+)`, 'g'))) {
            const custom = m[1].split('.').filter(part => part.startsWith('u_'));
            if (custom.length) found.add(m[1]);
        }
    };
    scan(JSON.stringify(plan.steps));
    return [...found].sort();
}

function headline(confidence: FlowPlanConfidence): string[] {
    if (confidence === 'partial') return ['// TODO(convert): only partly carried over; finish it from the notes below.'];
    if (confidence === 'manual') return ['// TODO(convert): design this step by hand from the notes below.'];
    return [];
}

function humanize(name: string): string {
    const words = name.replace(/_/g, ' ').trim();
    return words.charAt(0).toUpperCase() + words.slice(1);
}

function condition(c: FlowPlanCondition): string {
    return c.derived ? `\`${c.expression.replace(/`/g, '\\`')}\`` : "''";
}

function conditionComment(c: FlowPlanCondition): string[] {
    if (c.derived) return [];
    return notesComment([`write this condition: ${c.source}`], 'TODO(convert)');
}

/** Single-line notes as `//` comments; notes with line breaks (scripts) as a block. */
function notesComment(notes: string[], tag: string): string[] {
    const out: string[] = [];
    for (const note of notes) {
        const [first, ...rest] = note.replace(/\r\n/g, '\n').split('\n');
        out.push(...wrap(`${tag}: ${first}`, 110).map(l => `// ${l}`));
        if (rest.length) out.push(...blockComment(rest, ''));
    }
    return out;
}

function blockComment(lines: string[], pad: string): string[] {
    return [`${pad}/*`, ...lines.map(l => `${pad} *${l ? ` ${l.replace(/\*\//g, '*\\/')}` : ''}`), `${pad} */`];
}

function wrap(text: string, width: number): string[] {
    const words = text.split(' ');
    const lines: string[] = [];
    let line = '';
    for (const word of words) {
        if (line && line.length + word.length + 1 > width) {
            lines.push(line);
            line = `    ${word}`;
        } else line = line ? `${line} ${word}` : word;
    }
    if (line) lines.push(line);
    return lines;
}

function duration(seconds: number): string {
    const parts: string[] = [];
    let rest = Math.max(0, Math.round(seconds));
    for (const [unit, size] of [['days', 86400], ['hours', 3600], ['minutes', 60]] as const) {
        if (rest >= size) {
            parts.push(`${unit}: ${Math.floor(rest / size)}`);
            rest %= size;
        }
    }
    if (rest || !parts.length) parts.push(`seconds: ${rest}`);
    return `Duration({ ${parts.join(', ')} })`;
}

function columnType(type: string): 'string' | 'boolean' | 'integer' {
    if (/boolean/i.test(type)) return 'boolean';
    if (/integer/i.test(type)) return 'integer';
    return 'string';
}

function str(value: string): string {
    return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r/g, '\\r').replace(/\n/g, '\\n')}'`;
}

function escapeTemplate(text: string): string {
    return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function key(name: string): string {
    return /^[A-Za-z_$][\w$]*$/.test(name) ? name : str(name);
}

function camel(identifier: string): string {
    const name = identifier.replace(/_([a-z0-9])/g, (_m, c: string) => c.toUpperCase());
    return /^[a-z]/i.test(name) ? name : `flow${name}`;
}
