/**
 * Fluent (now-sdk) skeletons generated from flow conversion plans.
 */
import { describe, expect, it } from '@jest/globals';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
import { WorkflowExport } from '../../../../src/sn/workflow/WorkflowModels';
import { planFlowConversion } from '../../../../src/sn/workflow/WorkflowFlowConversion';
import { generateFluentFlow } from '../../../../src/sn/workflow/WorkflowFluentGenerator';
import { buildExport } from './workflowExportBuilder';

const fixture = (name: string): WorkflowExport => JSON.parse(readFileSync(new URL(`./fixtures/${name}.json`, import.meta.url), 'utf8')) as WorkflowExport;
const generate = (data: WorkflowExport): string => generateFluentFlow(planFlowConversion(data))[0].content;

/** Syntax errors only: the generated file is type-checked by the now-sdk build of the app it lands in. */
function syntaxErrors(source: string): string[] {
    const out = ts.transpileModule(source, { reportDiagnostics: true, compilerOptions: { target: ts.ScriptTarget.ES2022 } });
    return (out.diagnostics ?? []).map(d => ts.flattenDiagnosticMessageText(d.messageText, '\n'));
}

describe('generateFluentFlow: a catalog item workflow', () => {
    const [file] = generateFluentFlow(planFlowConversion(fixture('laptop-request')));
    const code = file.content;

    it('writes one .now.ts file under src/fluent/flows (or a given folder)', () => {
        expect(file.path).toBe('src/fluent/flows/laptop-request.now.ts');
        expect(generateFluentFlow(planFlowConversion(fixture('laptop-request')), { directory: 'src/fluent/converted/' })[0].path)
            .toBe('src/fluent/converted/laptop-request.now.ts');
    });

    it('is valid TypeScript', () => {
        expect(syntaxErrors(code)).toEqual([]);
    });

    it('imports only what it uses', () => {
        expect(code).toContain("import { Flow, action, trigger, wfa } from '@servicenow/sdk/automation'");
        expect(code).toContain("import { StringColumn } from '@servicenow/sdk/core'");
    });

    it('opens with the source, coverage and open decisions', () => {
        expect(code).toContain(' * Laptop Request: generated by now-sdk-ext from the legacy workflow "Laptop Request"');
        expect(code).toContain(' * Coverage: 5 steps carried over directly, 1 partly, 5 to design by hand.');
        expect(code).toContain(' * Open decisions:');
        expect(code).toContain(' * - [subflow] Provision account runs the workflow "Child provisioning"');
    });

    it('declares the flow, its flow variables and its catalog trigger', () => {
        expect(code).toContain("export const laptopRequest = Flow(\n    {\n        $id: Now.ID['laptop_request'],\n        name: 'Laptop Request',");
        expect(code).toContain("            ticket: StringColumn({ label: 'Ticket' }),");
        expect(code).toContain("wfa.trigger(trigger.application.serviceCatalog, { $id: Now.ID['laptop_request_trigger'] }, { run_flow_in: 'background' }),\n    (params) => {");
    });

    it('captures the approval and branches on its state', () => {
        expect(code).toContain("const manager_approval = wfa.action(action.core.askForApproval, { $id: Now.ID['laptop_request_manager_approval'], annotation: 'Legacy step 2: Manager approval' }, {");
        expect(code).toContain("users: [wfa.dataPill(params.trigger.request_item.requested_for.manager, 'reference')], groups: [], manual: false");
        expect(code).toContain('wfa.flowLogic.if({ $id: Now.ID[\'laptop_request_if_manager_approval\'], condition: `${wfa.dataPill(manager_approval.approval_state, "choice")}=rejected`');
        expect(code).toContain("wfa.flowLogic.endFlow({ $id: Now.ID['laptop_request_end_flow'], annotation: 'Legacy End' })");
    });

    it('writes field values as TemplateValue and text with data pills as template literals', () => {
        expect(code).toContain("values: TemplateValue({\n                    state: '4',\n                    comments: 'Rejected ${number}',\n                }),");
        expect(code).toContain('ah_subject: `Request ${wfa.dataPill(params.trigger.request_item.number, \'string\')} failed`,');
    });

    it('runs parallel lines in doInParallel', () => {
        expect(code).toContain("wfa.flowLogic.doInParallel(\n            { $id: Now.ID['laptop_request_parallel_after_order_and_account']");
    });

    it('marks what needs design work with TODO(convert) and the legacy script', () => {
        expect(code).toContain('// TODO(convert): Script: port it to a custom action with a script step');
        expect(code).toContain('         * workflow.scratchpad.ticket = current.number;');
        expect(code).toContain('// TODO(convert): write this condition: variables.needs_laptop=true');
        expect(code).toContain("wfa.flowLogic.if({ $id: Now.ID['laptop_request_if_needs_a_laptop'], condition: '',");
        expect(code).toContain('// TODO(convert): Continue at step 6 (Close complete), shared with other paths.');
    });

    it('gives every step its own id', () => {
        const ids = [...code.matchAll(/Now\.ID\['([^']+)'\]/g)].map(m => m[1]);
        expect(new Set(ids).size).toBe(ids.length);
    });
});

describe('generateFluentFlow: shapes', () => {
    it('writes a subflow with the record as its input, and record triggers for table workflows', () => {
        const activities = [
            { id: 'begin', type: 'Begin' },
            { id: 'set', type: 'Set Values', vars: { values: 'state=2' } },
            { id: 'end', type: 'End' },
        ];
        const edges: Array<[string, string, string]> = [['begin', 'Always', 'set'], ['set', 'Always', 'end']];
        const subflow = generate(buildExport({ table: 'incident', parents: ['Parent'], inputs: [{ name: 'u_level', type: 'integer' }], activities, edges }));
        expect(subflow).toContain("import { Subflow, action, wfa } from '@servicenow/sdk/automation'");
        expect(subflow).toContain("import { IntegerColumn, ReferenceColumn } from '@servicenow/sdk/core'");
        expect(subflow).toContain("record: ReferenceColumn({ label: 'Record', referenceTable: 'incident', mandatory: true }),");
        expect(subflow).toContain("u_level: IntegerColumn({ label: 'u_level' }),");
        expect(subflow).toContain("record: wfa.dataPill(params.inputs.record, 'reference'),");
        expect(syntaxErrors(subflow)).toEqual([]);

        const flow = generate(buildExport({ table: 'incident', condition: 'priority=1', activities, edges }));
        expect(flow).toContain("wfa.trigger(trigger.record.created, { $id: Now.ID['test_workflow_trigger'] }, { table: 'incident', condition: 'priority=1', run_flow_in: 'background' })");
    });

    it('leaves out params when the body never uses them', () => {
        const code = generate(buildExport({
            table: 'global',
            activities: [{ id: 'begin', type: 'Begin' }, { id: 'run', type: 'Run Script', vars: { script: 'gs.info("x");' } }, { id: 'end', type: 'End' }],
            edges: [['begin', 'Always', 'run'], ['run', 'Always', 'end']],
        }));
        expect(code).toContain('    () => {');
        expect(code).not.toContain('ReferenceColumn');
        expect(syntaxErrors(code)).toEqual([]);
    });

    it('runs a nested parallel block line by line (flows cannot nest them)', () => {
        const code = generate(buildExport({
            activities: [
                { id: 'begin', type: 'Begin' },
                { id: 'a', type: 'Log Message', vars: { message: 'a' } },
                { id: 'b', type: 'Branch', name: 'Inner' },
                { id: 'b1', type: 'Log Message', vars: { message: 'b1' } },
                { id: 'b2', type: 'Log Message', vars: { message: 'b2' } },
                { id: 'join', type: 'Join' },
                { id: 'end', type: 'End' },
            ],
            edges: [['begin', 'Always', 'a'], ['begin', 'Always', 'b'], ['a', 'Always', 'join'], ['b', 'Always', 'b1'], ['b', 'Always', 'b2'],
                ['b1', 'Always', 'join'], ['b2', 'Always', 'join'], ['join', 'Complete', 'end'], ['join', 'Incomplete', 'end']],
        }));
        expect(code.match(/doInParallel\(/g)).toHaveLength(1);
        expect(code).toContain('// line 1');
        expect(code).toContain('ran in parallel in the workflow');
        expect(syntaxErrors(code)).toEqual([]);
    });

    it('writes durations, flow variables and their conditions', () => {
        const code = generate(buildExport({
            activities: [
                { id: 'begin', type: 'Begin' },
                { id: 'wait', type: 'Timer', vars: { duration: '1970-01-01 01:30:00' } },
                { id: 'flag', type: 'Run Script', vars: { script: 'workflow.scratchpad.ok = true;' } },
                { id: 'check', type: 'If', vars: { advanced: 'true', script: "answer = workflow.scratchpad.ok ? 'yes' : 'no';" } },
                { id: 'log', type: 'Log Message', vars: { message: 'ok' } },
                { id: 'end', type: 'End' },
            ],
            edges: [['begin', 'Always', 'wait'], ['wait', 'Always', 'flag'], ['flag', 'Always', 'check'], ['check', 'Yes', 'log'], ['check', 'No', 'end'], ['log', 'Always', 'end']],
        }));
        expect(code).toContain("durationType: 'explicit_duration', duration: Duration({ hours: 1, minutes: 30 })");
        expect(code).toContain("ok: BooleanColumn({ label: 'Ok' }),");
        expect(code).toContain("params.flowVariables, {\n            ok: true,\n        })");
        expect(syntaxErrors(code)).toEqual([]);
    });

    it('escapes quotes, line breaks and comment ends from the workflow', () => {
        const code = generate(buildExport({
            name: "Bob's \"quoted\" workflow",
            activities: [
                { id: 'begin', type: 'Begin' },
                { id: 'log', type: 'Log Message', vars: { message: "it's `done`\nnext line" } },
                { id: 'run', type: 'Run Script', vars: { script: '/* a */ gs.info("*/ still a comment");' } },
                { id: 'end', type: 'End' },
            ],
            edges: [['begin', 'Always', 'log'], ['log', 'Always', 'run'], ['run', 'Always', 'end']],
        }));
        expect(code).toContain("name: 'Bob\\'s \"quoted\" workflow',");
        expect(code).toContain("log_message: 'it\\'s `done`\\nnext line',");
        expect(code).toContain('* /* a *\\/ gs.info("*\\/ still a comment");');
        expect(syntaxErrors(code)).toEqual([]);
    });

    it('says which custom fields need the app\'s table types', () => {
        const code = generate(buildExport({
            table: 'change_request', condition: 'type=normal',
            activities: [{ id: 'begin', type: 'Begin' }, { id: 'check', type: 'If', vars: { condition: 'u_hot_fix=true' } }, { id: 'log', type: 'Log Message', vars: { message: 'hot' } }, { id: 'end', type: 'End' }],
            edges: [['begin', 'Always', 'check'], ['check', 'Yes', 'log'], ['check', 'No', 'end'], ['log', 'Always', 'end']],
        }));
        expect(code).toContain('Custom fields used as data pills: u_hot_fix.');
        expect(code).toContain('run `now-sdk dependencies`.');
    });

    it('builds valid TypeScript from the merge-without-join fixture', () => {
        expect(syntaxErrors(generate(fixture('merge-without-join')))).toEqual([]);
    });
});
